#+OPTIONS: toc:t
# This is the actual README for the repo. README.md is generated by [C-c C-e m m].

* Installing and Contributing

*** Dependencies

  * [[https://www.python.org/downloads/][Python 3.7+]] :: Python 3 would technically be good enough but 3.7 is the
       version the virtual environment happens to be installed to.
  * [[https://pip.pypa.io/en/stable/installing/][pip]] :: Be sure that you install a version compatible with Python 3.7;
       depending on your system package manager, this may be under the `pip3`
       name (with `pip` defaulting to Python 2).
  * [[https://pipenv.readthedocs.io/en/latest/install/][pipenv]] :: This allows you to isolate this project's dependencies in its own
       virtual environment, without affecting your main Python installation.

* How to /Puflantu/

*** General Language Elements

Spelling is directly mapped onto pronunciation, which generally follows the
rules you'd expect for some kind of Romanized hybrid of Mandarin and Japanese.

Word order in Perflontus (Perflontus "/Puflantu/") is Subject-Object-Verb. Nouns
and adjectives always end in vowels. Verbs and adverbs always end in consonants.

#+BEGIN_EXAMPLE
Alisu  Puflantu    catub.
Alice  Perflontus  speak-she.
#+END_EXAMPLE

Descriptors are generally prepositive, i.e. they come before the things they
describe. In general Perflontus is head-final, meaning that the word that
defines the type of phrase it's in comes at the end of the phrase.

*** Sounds

Perflontus consists of 27 phonemes, which are mapped onto the English alphabet
plus apostrophe ='=.

***** Vowels

It has six vowels: ~a~, ~e~, ~i~, ~o~, ~u~, and ~w~. The first four are pronounced as they
are in Spanish or Japanese; in English these vowels appear in "car", "bait",
"feat", and "goat" respectively.

~u~ is pronounced as a schwa <ə>, which appears with some frequency in English
depending on how slack the speaker is in their unstressed syllables. Examples
are the "i" in "pencil", the "e" in "camera", or the second "o" in "chocolate".
<ʌ>, as in "butt", is a reasonable allophone.

~w~ is pronounced as <u>, the "oo" sound you'd expect ~u~ to make but it doesn't.
"Goon" and "pool" are good English examples.

***** Consonants

Of the consonants, ~b~, ~d~, ~j~, ~k~, ~l~, ~m~, ~n~, ~p~, ~r~, ~s~, ~t~, and ~z~ behave the way a
native English speaker would expect.

~f~ and ~v~ are close to normal for English but are actually mapped to <ɸ> and
<β> respectively, which are pronounced without using one's teeth. The "f" and
"v" in Japanese and Spanish are supposed to actually use these if you're not a
gaijin/gringo. English speakers will perceive that they are blowing more air
than usual when pronouncing these.

~y~ and ~g~ are <ɲ> and <ŋ> respectively; a reasonable shortcut for an English
speaker is to imagine a preceding "n" whenever these letters are encountered.
Italian and Spanish use "gn" and "ñ" respectively for <ɲ>. English "ng" is a
correct interpretation of <ŋ> but the phoneme will show up a lot more often
and in "unusual" places. For physiological reasons whenever two of ~g~, ~n~, and ~y~
appear adjacent to one another the first is pronounced as <n> regardless of
the actual spelling used.

~q~ and ~x~ are <tʃ> "ch" and <ʃ> "sh" respectively, corresponding to their use
in romanized Chinese.

~c~ is <ʒ>, the second half of the "j" phoneme. In English it appears as the "s"
in "leisure", the "g" in "concierge", or the second half of the "x" in "luxury".

~h~ is <x>, which is like English "h" but uses the back of the throat more. It's
all over the place in Hebrew/Yiddish, and its English usage is predominantly
in loan words from those language like the "ch" in "chutzpah". It is not quite
as rough as Klingon "H", because we aren't quite that deep into sci-fi tropes.

Finally, ~'~ is the sound of a bell. When pronouncing this as a human it is
sufficient to use a glottal stop instead -- that's the slight pause and buildup
of air that comes just before a lot of word-initial vowels in English. In
particular it happens just before both vowels in "uh-oh". For our audio work we
will overlay a bell sound on top of these pauses, so maybe draw them out a
little?

***** Syllables

Syllables in Perflontus always contain exactly one vowel, which may be preceded
by at most one consonant, and followed by at most one consonant. This means that
an English speaker must take care to pronounce vowel and consonant clusters as
though they contain a syllable break, even if the cluster would represent a
valid English diphthong. For example ~wfro~ should be pronounced as ~OOF-roh~ and
not ~OO-froh~; and ~riqwa~ as ~REE-choo-ah~ and not ~REACH-wah~ or ~REE-chwa~. When in
doubt a consonant belongs to the same syllable as the vowel following it, e.g.
~i-qa~ not ~iq-a~.

Stress occurs on the syllable preceding a word's final consonant, not counting
any particles. Thus for verbs the stress will fall on the final syllable; for
nouns, usually on the penultimate or antepenultimate.

#+BEGIN_EXAMPLE
A- la- nu   Puf- lan- tu   ca-  tub.
ah-LAH-nuh  puff-LAHN-tuh  zhah-TUB.

Bu- nu   pa- i   to- re- lw- a   im   w- la- toc.
BUH-nuh  PAH-ee  toh-RAY-loo-ah  EEM  oo-lah-TOZH.
#+END_EXAMPLE

*** Pronouns, Part 1 -- Personal Pronouns

Pronouns play a core role in Perflontic inflection, and therefore must be
addressed first. Perflontic pronouns have the following characteristics:

  * First/second/third person designations.
  * Subject/object designations. Formally the subject form is the nominative
    case, while the object form covers the oblique case, a.k.a. "everything
    else". (This is the same casing system English uses.)
  * Singular/dual/plural designations. The dual number refers specifically to
    two of a thing; thus separate pronouns are used to refer to "you, alone",
    "the two of you", and "y'all".
  * No gender distinctions, including for third person personals.
  * No sentience distinctions, i.e. he = she = it.

#+BEGIN_EXAMPLE
```
|    | Singular | Dual    | Plural  |
|----+----------+---------+---------|
| 1P | wm / um  | wn / un | wy / uy |
| 2P | iz / ez  | ij / ej | ix / ex |
| 3P | at / ot  | ab / ob | ad / od |
```
#+END_EXAMPLE

Note that all the pronouns are a vowel and a consonant. (This is the main
exception to the rule that noun-like things end in vowels.) Furthermore the
vowel does not depend at all on the number, and the consonant does not depend at
all on the case.

*** Verbs, Part 1 -- Basic Infixes

Verbs have a root form which is inflected in various ways. In particular, the
root form of a verb is not a valid word unto itself. The most common way a verb
is inflected is to indicate its subject, object, and negation. This is done
through the use of infixes. The point at which a verb accepts infixes is always
immediately before its final vowel. To help in remembering this, the root form a
verb is always written with an asterisk indicating this position.

#+BEGIN_EXAMPLE
wl*oc    "to eat"
wlwmoc   eat-1S "I eat"
wlizoc   eat-2S "you eat"
#+END_EXAMPLE

Each verb accepts up to three infixes, in the following order:

  * A subject pronoun, as described above. This is always present if the verb
    form is being used as a verb, even if the subject is explicitly named
    elsewhere in the sentence. (It may be absent in cases where the verb form is
    used to derive a noun.)

#+BEGIN_EXAMPLE
```
Andursun  ke   toreli  wl[at]oc.
Anderson  one  cookie  eat-3S.
Anderson eats a cookie.

Ke   toreli  wl[at]oc.
One  cookie  eat-3S.
He eats a cookie.

Andursun ke toreli *wloc. -- Incorrect, [at] infix must still be provided.
```
#+END_EXAMPLE

  * A negation infix ~ey~. This indicates the negation/lack of the action, /not/ a
    reversal of the action. The corresponding distinction can be seen in English
    where "to not do" something is distinct from "to undo" it; this is the
    former.

#+BEGIN_EXAMPLE
```
Canik    kofuri  ratiq.
Yannick  coffee  drink-3S.
Yannick drinks coffee.

Canik    enxura  rat[ey]iq.
Yannick  water   drink-3S-NEG.
Yannick does not drink water.
```
#+END_EXAMPLE

  * An object pronoun, as described above. This is present to the degree that
    it needs to be for disambiguation:

#+BEGIN_EXAMPLE
```
Dani   qek[wm]ad.
Danny  meet-1S.
I meet Danny.

Qek[wm][ot]ad.
Meet-1S-3O.
I meet him.

Dani   qek[wm][ot]ad. -- Valid with redundant 3O infix; may indicate emphasis.
Danny  meet-1S-3O.
I meet *Danny*.
```
#+END_EXAMPLE

*** Pronouns, Part 2 -- This, That, A, and The

"This" and "that" are demonstrative pronouns that differ from regular nouns
primarily in that they have special handling for their objective and possessive
cases that regular nouns don't. They are otherwise handled like regular nouns,
and in particular pluralized like them. These rules will be discussed later; for
now, the following table should suffice:

#+BEGIN_EXAMPLE
|      | Singular  | Dual      | Plural      |
|------+-----------+-----------+-------------|
| This | ita / eta | itw / etw | itwa / etwa |
| That | iqa / eqa | iqw / eqw | iqwa / eqwa |
#+END_EXAMPLE

Like most Perflontus nouns (again, to be covered more thoroughly later), ~ita~ et
al. may also be used as demonstrative adjectives.

#+BEGIN_EXAMPLE
Demiunu  etwa       torelwa  et   wlatoc.
Damien   these-OBJ  cookies  FUT  eat-3S.
Damien will eat these cookies.

Demiunu  etwa       et   wlatoc.
Damien   these-OBJ  FUT  eat-3S.
Damien will eat these.

Ita       somatotun.
This-SUB  please-3S-3O.
This pleases him.
#+END_EXAMPLE

There is no direct equivalent for the definite article "the". Depending on the
context it is correct to either omit any qualifier at all or to use "this" or
"that" as appropriate instead.

Similarly there is no directly equivalent to the indefinite article "a(n)". When
it is necessary to refer to some indefinite item ~ke~ (literally "one") is used
instead.

#+BEGIN_EXAMPLE
Tusvo  yipox  et   capatil.
Bus    soon   FUT  arrive-3S.
(The) bus will arrive soon.

Ke   tusvo  yipox  et   capatil.
One  bus    soon   FUT  arrive-3S.
A bus will arrive soon.

Iqa   ke   tusvo  yipox  et   capatil.
That  one  bus    soon   FUT  arrive-3S.
The 1 bus will arrive soon.
#+END_EXAMPLE
