* Installing and Contributing

*** Dependencies

  * [[https://www.python.org/downloads/][Python 3.7+]] :: Python 3 would technically be good enough but 3.7 is the
       version the virtual environment happens to be installed to.
  * [[https://pip.pypa.io/en/stable/installing/][pip]] :: Be sure that you install a version compatible with Python 3.7;
       depending on your system package manager, this may be under the `pip3`
       name (with `pip` defaulting to Python 2).
  * [[https://pipenv.readthedocs.io/en/latest/install/][pipenv]] :: This allows you to isolate this project's dependencies in its own
       virtual environment, without affecting your main Python installation.

*** Contributing

Artifacts should be created directly in the =artifacts/= folder. Regardless of
what form your artifact takes, a written transcription of its relevant
Perflontus content should be provided as a like-named =.md=, =.org=, or =.txt= file.
Be sure to also add any new vocabulary to the proper =root_*.tsv= file.

The =root_*.tsv= files are lists of tab-separated (word, definition) pairs. They
are ordered vaguely by semantic category so as to better demonstrate what gaps
we have in the lexicon. Comments may be placed on their own line starting with
=#=.

To run any of the scripts, you will need to be in an appropriately configured
pipenv environment. Running =pipenv install= in this project's root directory
should create a virtual environment with all the project's (Python)
dependencies. Then =pipenv shell= will put you into the virtual environment. Use
=exit= to return to your original shell.

The =explain_duplicates.sh= shell script checks the entire lexicon for duplicates,
including on inflections, and tells you the inflections that are causing
collision. If you have a word which you are sure will not be inflected, or one
that violates certain morphological rules on a one-off basis (for example, a
short noun that ends in =-w=), place it in =root_closed.tsv= instead of
=root_nouns.tsv= or =root_verbs.tsv=. Adverbs that are formed from adjectives by
suffixing =-s= should be entered in adjectival form in =root_nouns=; adverbs that
don't have that derivation should go in =root_closed= (for now).

=phones.py= can be used to generate a few Perflontus-valid words at random, which
can be useful to avoid personal biases about what phonemes to use.

***** Using Github's Web Interface

A few useful things to know when editing via the web interface alone:

  * Tabs can be inserted for a =.tsv= file by setting the indentation mode in the
    top right to "Tabs" instead of "Spaces".
  * If you're planning to make multiple changes to one file, or changes to
    multiple files, group your changes together by committing to your own
    branch. (An option using these words should appear at the bottom of your
    editing interface.) Afterwards, you can make a pull request from your branch
    to submit your full set of changes.

* Speaking and Writing Perflontus

Documentation on how the actual language works is provided [[file:doc/main.org][here]].
