* General Language Elements

Spelling is directly mapped onto pronunciation, which generally follows the
rules you'd expect for some kind of Romanized hybrid of Mandarin and Japanese.

Word order in Perflontus (Perflontus "/Puflantu/") is Subject-Object-Verb. Unlike
many natural SOV languages, there are no particle markers for subject and
object, so word order is somewhat more constrained.

Nouns and adjectives always end in vowels; in addition, the boundaries between
these two parts of speech are rather fluid, and many words that function as one
also function as the other. Verbs and adverbs always end in consonants (though
the definition of "adverb" is somewhat loose). Verbs have a root form which is
never used directly; instead, a large body of affixes is used to inflect the
root form with syntactic and semantic meaning.

#+BEGIN_EXAMPLE
Alisu  Puflantu    catub.
Alice  Perflontus  speak-she.
Alice speaks Perflontus.
#+END_EXAMPLE

Descriptors are generally prepositive, i.e. they come before the things they
describe. Conversely, things that appear in English as prepositions generally
appear as /post/-positions in Perflontus. To put it another way, Perflontus is
strongly head-final, meaning that the word that defines the type of phrase it's
in comes at the end of the phrase.

#+BEGIN_EXAMPLE
Honwze  jozrwpo  entuyice  tis     im   kanwmwj.
blue    shirt    store     at-ADV  PST  buy-1S
I bought a blue shirt at the store.
#+END_EXAMPLE

(Note that because of noun/adjective duality and the lack of markers, it is up
to the listener to determine that the speaker does not intend something like ~I
bought a blue (thing) at the shirt store~ or ~I bought (the color/concept) blue at
the shirt store~.)

* How to /Puflantu/

  * [[file:phonetics.org][Phonetics]] :: How to pronounce all the words
  * [[file:pronouns.org][Pronouns]] :: Pronouns and other stand-ins
  * [[file:verbs.org][Verbs]] :: Verbs and their affix inventory
  * [[file:nouns.org][Nouns]] :: Nouns and adjectives

*** Pedagogic Ordering

  * [[file:phonetics.org][Phonetics]] :: How to pronounce all the words
  * [[file:pronouns.org#personal-pronouns][Personal Pronouns]] :: Personal pronouns (I, they, y'all, et al.)
  * [[file:verbs.org#basic-infixes][Basic Verbal Inflection]] :: Inflections for basic SOV constructions
  * [[file:pronouns.org#determinatives-and-demonstratives][This, That, A, and The]] :: Determinative and demonstrative pronouns
  * [[file:verbs.org#tense-aspect-and-mood][Tense, Aspect, and Mood]] :: On time, duration, and reality
  * [[file:nouns.org][Noun and Adjective Basics]] :: Number and negation
  * [[file:verbs.org#to-be][To Be]] :: Handling the most common copula
  * [[file:nouns.org#verb-derived-nouns-and-adjectives][Verb-Derived Nouns]] :: Nominalizing suffixes e.g. -er, -ing, -tion

*** Genitive (Possessive) Case

For nouns, the possessive case is marked simply by suffixing =-ro=. This
possessive form works as both a noun and an adjective.

#+BEGIN_EXAMPLE
Alanu-ro  kude  emkixa  zat.
Alan-GEN  book  red     be-3S.
Alan's book is red.

Robu-ro  honwze  zat.
Rob-GEN  blue    be-3S.
Rob's is blue.
#+END_EXAMPLE

Note that there are two potential points for numeric inflection here: The root
noun is inflected to indicate the number of possessors, while the =-ro= suffix may
be inflected to indicate the number of possessed objects.

#+BEGIN_EXAMPLE
Justiinu-rwe    kudwe    kolbawe   zad.
Justine-GEN-PL  book-PL  green-PL  be-3pS.
Justine's books are green.

Yelafwe-ro        kude  wre    zat.
Learn-AGT-PL-GEN  book  black  be-3S.
The students' book is black.

Yelafwe-rwe          kworwe       apwe      zad.
Learn-AGT-PL-GEN-PL  clothing-PL  white-PL  be-3pS
The students' clothes are white.
#+END_EXAMPLE

Possessive pronouns are formed by infixing the /subject/ form of the pronoun into
=r*o=. This applies to all personal pronouns, their interrogative forms (=wat= et
al, described in more detail later), and to =ita= "this" and =iqa= "that". As with
regular nouns, it is important to pay attention to the difference in inflection
for the number of possessors vs the number of possessed things.

#+BEGIN_EXAMPLE
Itwe     torelwe    rwmwe     zad.
this-PL  cookie-PL  1-GEN-PL  be-3pS.
These cookies are mine.

Iqa   toreli  rixe    zat.
that  cookie  2p-GEN  be-3S.
That cookie is y'all's.

Rwatwe      zad    na.
Who-GEN-PL  be-3S  ?
Whose are those?
#+END_EXAMPLE

*** Adjectives and Noun Classes (STUB)

Some nouns have classes which apply an additional mutation to the word. If this
occurs, all non-numeric adjectives for that noun take the mutation as well. This
mutation happens before polarity, numeric, and comparative inflection. It
applies across the copula but only when the object complement is an adjective.

  * Bodily actions (W) :: Replace the final consonant cluster ~(C+)~ with ~\1w\1~.
  * Light sources (T) :: If the first vowel is ~(V)~, prefix ~\1t~.
  * Fluids (R) :: If the first two vowels are ~(V)(V)~, replace with ~\1r\2~. If the
                  first two vowels are ~(VC+)(V)~, replace with ~\1ur\2~.

*** Comparatives and Superlatives (STUB)

Comparatives are formed by suffixing ~'fi~ . This happens after negation but before
numeric inflection. The corresponding dual and plural forms are ~'fw~ and ~'fwe~.

Some types of adjectives do not permit standard comparative formation. Instead,
these take on ~ogi'fi~ as adverbial modifiers, in the same way "more" is used
instead of "-er" in English, e.g. "bigger" vs "more gigantic".

Superlatives are formed by suffixing ~'~ , ~'w~, or ~-'we~ respectively. Adjectives
that use ~ogi'fi~ instead of ~-'fi~ also take ~ogi'~ instead of ~-'~.

*** Pronouns, Part 3 -- Indefinite Pronouns and Other Stand-Ins (STUB)

|               | this    | that    | some    | no      | every  | any     | interr.     |
| person/thing  | ita/eta | iqa/eqa | orvo    | yemo    | axwe   | veli    | wat/.../wod |
| place ~hanu~    | tihan   | alhan   | orhan   | yehan   | axwhan | velhan  | whan        |
| time ~bwri~     | tibwr   | albwr   | orbwr   | yebwr   | axwbwr | velbwr  | wbwr        |
| way ~zove~      | tizov   | alzov   | orzov   | yezov   |        | velzov  | wzov        |
| reason ~dule~   | tidul   | aldul   | ordul   | yedul   |        | veldul  | wdul        |
| quantity ~lera~ | tilerwe | alerwe  | orlerwe | yelerwe |        | velerwe | wlerwe      |

***** Notes

  * ~Axwe~ "every" is always plural in Perflontus; there is not singular
    inflection. It also imposes the plural inflection on anything in modifies.
    This is counter to many languages where "every" is frequently singular, e.g.
    "everything", "cada vez", "tout".
  * For similar reasons the same is true of all the quantity forms.
  * The "this" and "that" forms of most things do not take a subject/object
    inflection.
  * The various forms referring to place, time, way, and reason are
    systematically formed from their nouns, but also drop the final vowel in
    their converstion to adverbs.
  * ~tizov~ "this-way" and ~tidul~ "this-reason" are both reasonably glossed as
    "if", but ~tizov~ is used in cases where the if-clause indicates a mechanical
    cause for something, whereas ~tidul~ indicates more abstract causality.
    Another way to put it, which also applies to ~alzov~ and ~aldul~ in the opposite
    direction, is that ~*zov~ clauses are answers to questions better phrased as
    "how", while ~*dul~ clauses are answers to questions better phrased as "why".

*** Questions (STUB)

A sentence-final ~na~ marks questions. This is sufficient to make a sentence
interrogative; no further word order changes are required.

#+BEGIN_EXAMPLE
Os wlizoc  na.
eat-2S-PRF ?
Have you eaten?

Zo,  os wlwmoc.
yes  eat-1S-PRF.
Yes, I have eaten.
#+END_EXAMPLE

The interrogative personal pronoun is the corresponding third person pronoun
prefixed by ~w-~. (~wat/wot~, ~wab/wob~, ~wad/wod~) This pronoun works for "who",
"what", and "which". The genitive forms are ~rwato~, ~rwabo~, and ~rwado~ -- recall
that the pronoun infixed into ~r*o~ indicates the number of possessors but always
takes the subjective case.

#+BEGIN_EXAMPLE
Wad     et   qekadumad    na.
Who-PL  FUT  meet-3pS-1O  ?
Who will meet me?

Wod      et   qekwmodad    na.
Whom-PL  FUT  meet-1S-3pO  ?
Whom will I meet?

Rwato    daxafe     zat    na.
Who-GEN  teach-AGT  be-3S  ?
Whose teacher is she? -- Depending on context, might also be "Which (subject's) teacher"
#+END_EXAMPLE

Additional interrogatives are shown in the table in the previous section. In the
same way that questions don't take on a different word order than declarative
sentences, those interrogatives still take a "normal" word order, e.g. =wbwr=
"when" takes the same position that a time-marking adverb would take in a
declarative sentence.

#+BEGIN_EXAMPLE
Janu  wbwr  et qekatuyad     na.
Jon   when  meet-3S-1pO-FUT  ?
When will Jon meet us?

Janu  tiroqas    et qekatuyad.
Jon   today-ADV  meet-3S-1pO-FUT.
Jon will meet us today.
#+END_EXAMPLE

*** Numbers (STUB)

Perflontus uses a base 6 system. The numbers 0-6 are ~ri~, ~ke~, ~ha~, ~pai~, ~uqi~, ~lo~,
and ~aqe~.

Multiples of 6 up through 30 are formed by dropping all the final vowels from
the sixes digit and suffixing ~aqe~: ~aqe~, ~haqe~, ~paqe~, ~uqaqe~, ~laqe~. Adding units
digits replaces the final ~u~; the multiples of 7 through 35 are ~aqke~, ~haqha~,
~paqpai~, ~uqaquqi~, and ~laqlo~.

The next powers of 6 up through 6^5 are ~yo~, ~sa~, ~toe~, and ~wdo~. To count multiples
of these, prefix the entirety of the corresponding hexit, e.g. ~keyo~, ~hayo~,
~paiyo~, ~uqiyo~, ~loyo~. Note that unlike ~aqe~, in all these cases the presence of a 1
hexit is explicit: ~keyo~, ~kesa~, ~ketoe~, ~kewdo~. Additional hexits are added as
separate words, e.g. 1023 = 4423_6 = ~uqisa uqiyo kaqpai~.

Powers of 6 above 6^5 are formed by naming the exponent, then replacing the
final vowel with ~wdo~: ~aqe~ \rightarrow ~aqwdo~, ~aqke~ \rightarrow ~aqkwdo~, etc. These
are still "unit" power-of-6 words, and to express an actual quantity still
require the explicity 1 hexit: ~keaqwdo~, ~keaqkwdo~, ~keaqhawdo~, etc.

Exact numbers do not take any additional inflection. For example "three dances"
is ~pai hinalwla~, not ~*pwpai hinalwla~. When measures of things are used -- for
example, "5 cups of water" -- the things being measured are taken as an
adjective for the number and the unit of measure. In this case we would
translate "water 5 cups", or =enxa lo janwe=. Note that not only is the noun class
applied to the unit of measure, it is also not applied to the thing being
measured, since it is not the head of its noun phrase (it is treated as an
adjective).

Inexact numbers are treated as units of measure unto themselves, e.g. "dozens of
dances" \rightarrow =hinala haqwe= "dance dozens".

Ordinal numbers are formed by the suffix =-ru=. This is subject to
adverbialization by an added =-s=.

*** Conjunctions (STUB)

Conjunctions in Perflontus are particles added to the end of each element they
link, save for the last.

#+BEGIN_EXAMPLE
Setu  ha  wibalw  -li  twipe  -li  oku    solatodov.
Seth  2   egg-DU  -&   sugar  -&   flour  need-3S-3pO
Seth needs two eggs, sugar, and flour.
#+END_EXAMPLE

Much like adjectives take =-s= to become adverbial when modifying verbs,
conjunctions take =-s= when linking lists of verbs or clauses.

#+BEGIN_EXAMPLE
Ogwris        wlwmoc  -lis    zumwmuz.
frequent-ADV  eat-1S  -&-ADV  sleep-1S
I eat and sleep a lot.
#+END_EXAMPLE

The full list of coordinating conjunctions is as follows:

| -li(s) | and                        | Emkixa-li kolbao zat.        | It is red and green.              |
| -di(s) | but, yet (contrastive and) | Ogis lifwman-dis uyis ywmel. | I study a lot but learn little.   |
| -ni(s) | then (sequential and)      | Bastonu-ni Yw Iorka twyex.   | We went to Boston, then New York. |
| -fo(s) | exclusive or               | At-fo wm cwnub.              | Either he or I will speak.        |
| -vo(s) | inclusive or               | Paliso-vo twipe orcizal na.  | Do you want milk and/or sugar?    |

Note that the inflection of the verb, where appropriate, is based on the
combination of all list elements for both "and" and "or". (This is in contrast
to English, where the inflection of the verb matches the /last/ list element in
the "or" case.) As an example, the exclusive-or sentence above uses the
first person dual =c[wn]ub= instead of the first person singular =c[wm]ub=.

  * -xa(s) :: for, because
  * -ja(s) :: so, therefore

(A bunch of these only make sense when attaching clauses, and in those cases
we'd rather so some kind of ~al* ... -ka(s)~ construction. Come back to this
later.)

Section on comparatives should incorporate the conjunctions for "...as X as Y"
and "...more/less X than Y".

*** Dependent Clauses (STUB)

A dependent clause is indicated by the attachment of the ~-ka~ suffix to its main
verb. ~-kas~ is used in the case where the dependent clause modifies a verb. A
reasonable English gloss for =-ka= is "that", but we'll see that many dependent
clauses use the =-ka= construction regardless of what their English translation
would use for the linking word. (One way to think about this is that many
dependent clauses in English can be rephrased to use "that" as their relative
pronoun, even if the result is more verbose.)

Dependent clauses can require the use of the relative personal pronoun, whose
forms are as follows:

The relative pronoun indicates the role that "that" within the clause if the
clause were rephrased as a standalone sentence. Further examples below will help
illustrate how this is decided.

***** That/What/Which Clauses and Participial Phrases

Clauses and phrases whose relative pronoun is "that", "who", "which", or "what"
use the relative personal pronoun, whose forms are as follows:

#+BEGIN_EXAMPLE
|     | Singular | Dual    | Plural          |
|-----+----------+---------+-----------------|
| REL | al / ol  | ar / or | ary(u) / ory(u) |
#+END_EXAMPLE

(Like other pronouns, these may appear as standalone words in addition to being
used as verbal infixes. However, since =ary= and =ory= are invalid words due to
syllable patterns, they take on an extra vowel when appearing alone.)

The relative pronoun inflects like other person pronouns with respect to its
role in subordinate clause.

#+BEGIN_EXAMPLE
Im   wlwm[ol]oc  -ka   um  im   somatun.
PST  eat-1S-RO   -DEP  1O  PST  please-3S.
What I ate pleased me.

Av   c[ary]ub   -ka  gwmeyir.
IMP  speak-RpS  DEP  know-1S-NEG
I don't know who-all is speaking.
#+END_EXAMPLE

Not all noun clauses actually use their relative pronoun. For example, in some
English "that" clauses, the "that" serves no other purpose other than to mark
that a subordinate clause exists. (For example, "that a subordinate clause
exists" in the previous sentence.) In these cases a relative pronoun is not used
at all; the indication of a subordinate clause using =-ka= suffices.

#+BEGIN_EXAMPLE
Im   wlwmoc  -ka   um  im   somatun.
PST  eat-1S  -DEP  1O  PST  please-3S.
That I ate pleased me.  (i.e. "The fact that I ate...")

Im   wlwm[ory]oc  -ka   um  im   somatun.
PST  eat-1S-RpO   -DEP  1O  PST  please-3S.
The things that I ate pleased me.

Imor     c[ad]ub    -ka   im   gwmeyir.
PST-IMP  speak-3pS  -DEP  PST  know-1S-NEG.
I didn't know that they had spoken.

Imor     c[ary]ub   -ka   im   gwmeyir.
PST-IMP  speak-RpS  -DEP  PST  know-1S-NEG.
I didn't know the people that had spoken.
#+END_EXAMPLE

Note that in the second example, the use of the infixed relative pronoun =ory=
carries extra information, namely that the object of "ate" is plural. In English
the introduction of extra words "The things" is necessary to translate the
sentence. Going in the other direction, it is important to omit words of that
type, as Perflontus' noun-adjective duality presumes "things" as the noun
whenever an adjective-like thing is used with no apparent modification target.

#+BEGIN_EXAMPLE
[Honwzwe  oryu  im   wlwmoc  -ka]   um  im   somatun.
[blue-PL  RpO   PST  eat-1S  -DEP]  1O  PST  please-3S.
[The blue things that I ate] pleased me.
          ^ here the pronoun is used to indicate the role of the things
            described by the subordinate clause

[Im   wlwmoryoc   -ka]   honwzwe  um  im   somatun.
[PST  eat-1S-RpO  -DEP]  blue-PL  1O  PST  please-3S.
The [me-eaten] blue things pleased me.
               ^ here 'honwzwe' suffices on its own for 'blue things'

[Honwzwe  im   wlwmoc  -ka]   um  im   somatun.
[blue-PL  PST  eat-1S  -DEP]  1O  PST  please-3S.
[That I ate the blue things] pleased me.

*[Im   wlwmoc   -ka]   honwzwe  um  im   somatun.    -- Incorrect
*[PST  eat-1S   -DEP]  blue-PL  1O  PST  please-3S.
*The [that I ate] blue things pleased me.
#+END_EXAMPLE

Participles in general are implemented as dependent clauses, with the exception
of the present participle of an active verb, for which the [[Gerund Case ~-a~][gerund case]] may be
used. Generally these use a passive voice construction inside a dependent
clause, as follows:

#+BEGIN_EXAMPLE
Enxura   lirwmwb.
water-R  boil-1S
I boil the water.

Enxura   lirotwb.
water-R  boil-3O
The water boils.

Lirotwb-ka   enxura   rwmiq.
boil-3O-DEP  water-R  drink-1S
I drink the boiling water. (I drink the water that boils / is being boiled.)
       ^ note that the R noun class is not reflected in the clause

Im   lirotwb-ka   enxura   rwmiq.
PST  boil-3O-DEP  water-R  drink-1S.
I drink the boiled water. (I drink the water that was boiled.)
#+END_EXAMPLE

***** Location and Timing - When, Where

Clauses with additional connotations express them with an =al-= word, placed at
the beginning of the clause. These words are defined in [[Pronouns, Part 3 -- Indefinite Pronouns and Other Stand-Ins (STUB)][Indefinite Pronouns and
Other Stand-Ins]]; the relevant ones are:

| that-place ("where")            | alhan |
| that-time ("when")              | albwr |

Various relationships between clauses can be described using these words, along
with locative descriptors.

#+BEGIN_EXAMPLE
Alhan       xoale  jatif     -ka,  e'a   jatif.
that-place  smoke  exist-3S  -DEP  fire  exist-3S
Where there is smoke, there is fire.
#+END_EXAMPLE

Perflontus uses an inner-outer spatial metaphor for expressing time; things that
happened before the present are inside it, while things that happen afterward
are outside it.

***** Causation and Intent - How, Why

It is common for subordinate clauses and phrases to express some kind of
causality or intent. Much like the spatial/temporal clauses, causative clauses
are introduced by one of the following adverbs:

| this-method | that-method | this-reason | that-reason |
| tizov       | alzov       | tidul       | aldul       |

The distinction between -method and -reason is somewhat blurred, but the general
idea is that -method should be used when the clause refers to a mechanical cause
for something, whereas -reason should be used for more abstract causes. It is
expected that certain situations could be interpreted in either way, and it is
up to the speaker's discretion to choose one.

The choice between this- and that- depends on whether the causing event is in
the subordinate clause, or in the main clause. To put it another way, if a this-
adverb is used, the direction of causality or inference flows from the
subordinate clause to the main clause. If a that- adverb is used, the opposite
is true.

#+BEGIN_EXAMPLE
E'a   tidul        xoale  jatif      -kas      jatif.
fire  this-reason  smoke  exists-3S  -DEP-ADV  exists-3S
If there is smoke, there is fire.

Xoale  tizov        e'a   jatif      -kas      jatif.
smoke  this-method  fire  exists-3S  -DEP-ADV  exists-3S
If there is fire, there is smoke.
#+END_EXAMPLE

In both of the above examples, a this- adverb is used because the logical
direction of events is from the dependent clause to the main clause. In the
first example, the nature of the logic is by inference, so a -reason adverb is
used. In the second example, there is a concrete, mechanical cause in play, so a
-method adverb is used.

#+BEGIN_EXAMPLE
E'a   alzov        xoale  jatif      -kas      jatif.
fire  that-method  smoke  exists-3S  -DEP-ADV  exists-3S
There is fire, therefore there is smoke.

Xoale  aldul        e'a   jatif      -kas      jatif.
smoke  that-reason  fire  exists-3S  -DEP-ADV  exists-3S
There is smoke, therefore there is fire.
#+END_EXAMPLE

Each of the original examples can be inverted simply by changing the adverb
used. Now in the first example, the fire in the main clause is causing the smoke
in the dependent clause, so =alzov= is used to indicate the direction and that
there is a mechanical reason behind it. Similarly, in the second case, the
existence of the fire in the dependent clause is being inferred from the smoke
in the main clause, so =aldul= is used to indicate the direction and that the
reasoning is abstract.

***** Comparative Clauses (STUB)

Comparisons are always expanded to a full clause. Instead of =-ka= the
subordinate verb takes the particle =-sos=, and the use of the relative pronoun
in the clause indicates the role of the thing being compared.

*** Adpositions

  * -uxo
  * -uqo

*** Adverbs (STUB)

Adverbs are formed by suffixing ~s~. This also applies to particles.
*** Verbs, Part N -- Imperatives and Instructions (STUB)

The imperative voice is indicated by prefixing the active verb with ~'~. The most
polite forms, as might be used by a manual, inflect the verb as though using the
passive voice, i.e. omitting the "you" subject. Direct, more "blunt" forms
address, add the subject pronoun infixes.

* How to /Puflantu/, Abridged (Reference Tables)

*** Nouns

  * Always end in a non-"w" vowel.
  * Dual number converts the final vowel to =-w=. Plural number to =-we=.

*** Adjectives

  * Always end in a non-"w" vowel.
  * Inflect number to match the modified noun.
  * Come before the noun they modify.
  * Infix =-ay-= before the final vowel to negate.
  * Suffix =-s= to convert to an adverb.

*** Pronouns

***** Personal Pronouns

|        | Singular  | Dual      | Plural      |
|        | Subj/Obj  | Subj/Obj  | Subj/Obj    |
|--------+-----------+-----------+-------------|
| 1st    | wm / um   | wn / un   | wy / uy     |
| 2nd    | iz / ez   | ij / ej   | ix / ex     |
| 3rd    | at / ot   | ab / ob   | ad / od     |
| REL    | al / ol   | ar / or   | ary / ory   |
| "this" | ita / eta | itw / etw | itwe / etwe |
| "that" | iqa / eqa | iqw / eqw | iqwe / eqwe |
| "what" | wat / wot | wab / wob | wad / wod   |

***** Possessive Pronouns

All the items in the list below indicate a singular possessed object. Instead,
the table indicate the number of possessors. Inflect the resulting word as you
would a normal noun, e.g. =rwmo= \rightarrow =rwmw= / =rwmwe=.

|        | Singular | Dual  | Plural |
|--------+----------+-------+--------|
| 1st    | rwmo     | rwno  | rwyo   |
| 2nd    | rizo     | rijo  | rixo   |
| 3rd    | rato     | rabo  | rado   |
| REL    | ralo     | raro  | raryo  |
| "this" | ritao    | ritwo | ritweo |
| "that" | riqao    | riqwo | riqweo |
| "what" | rwato    | rwabo | rwado  |

***** Indefinite Pronouns

|               | this    | that    | some    | no      | every  | any     | interr.     |
|---------------+---------+---------+---------+---------+--------+---------+-------------|
| person/thing  | ita/eta | iqa/eqa | orvo    | yemo    | axwe   | veli    | wat/.../wod |
| place ~hanu~    | tihan   | alhan   | orhan   | yehan   | axwhan | velhan  | whan        |
| time ~bwri~     | tibwr   | albwr   | orbwr   | yebwr   | axwbwr | velbwr  | wbwr        |
| way ~zove~      | tizov   | alzov   | orzov   | yezov   |        | velzov  | wzov        |
| reason ~dule~   | tidul   | aldul   | ordul   | yedul   |        | veldul  | wdul        |
| quantity ~lera~ | tilerwe | alerwe  | orlerwe | yelerwe |        | velerwe | wlerwe      |
