#+TITLE: The Sounds of Perflontus

Perflontus consists of 27 phonemes, which are mapped onto the English alphabet
plus apostrophe ='=.

*** Vowels

It has six vowels: ~a~, ~e~, ~i~, ~o~, ~u~, and ~w~. The first four are pronounced as they
are in Spanish or Japanese; in English these vowels appear in "car", "bait",
"feat", and "goat" respectively.

~u~ is pronounced as a schwa <ə>, which appears with some frequency in English
depending on how slack the speaker is in their unstressed syllables. Examples
are the "i" in "pencil", the "e" in "camera", or the second "o" in "chocolate".
<ʌ>, as in "butt", is a reasonable allophone.

~w~ is pronounced as <u>, the "oo" sound you'd expect ~u~ to make but it doesn't.
"Goon" and "pool" are good English examples.

*** Consonants

Of the consonants, ~b~, ~d~, ~j~, ~k~, ~l~, ~m~, ~n~, ~p~, ~r~, ~s~, ~t~, and ~z~ behave the way a
native English speaker would expect.

~f~ and ~v~ are close to normal for English but are actually mapped to <ɸ> and
<β> respectively, which are pronounced without using one's teeth. The "f" and
"v" in Japanese and Spanish are supposed to actually use these if you're not a
gaijin/gringo. English speakers will perceive that they are blowing more air
than usual when pronouncing these.

~y~ and ~g~ are <ɲ> and <ŋ> respectively; a reasonable shortcut for an English
speaker is to imagine a preceding "n" whenever these letters are encountered.
Italian and Spanish use "gn" and "ñ" respectively for <ɲ>. English "ng" is a
correct interpretation of <ŋ> but the phoneme will show up a lot more often
and in "unusual" places. For physiological reasons whenever two of ~g~, ~n~, and ~y~
appear adjacent to one another the first is pronounced as <n> regardless of
the actual spelling used.

~q~ and ~x~ are <tʃ> "ch" and <ʃ> "sh" respectively, corresponding to their use
in romanized Chinese.

~c~ is <ʒ>, the second half of the "j" phoneme. In English it appears as the "s"
in "leisure", the "g" in "concierge", or the second half of the "x" in "luxury".

~h~ is <x>, which is like English "h" but uses the back of the throat more. It's
all over the place in Hebrew/Yiddish, and its English usage is predominantly
in loan words from those language like the "ch" in "chutzpah". It is not quite
as rough as Klingon "H", because we aren't quite that deep into sci-fi tropes.

Finally, ~'~ is the sound of a bell. When pronouncing this as a human it is
sufficient to use a glottal stop instead -- that's the slight pause and buildup
of air that comes just before a lot of word-initial vowels in English. In
particular it happens just before both vowels in "uh-oh". For our audio work we
will overlay a bell sound on top of these pauses, so maybe draw them out a
little?

*** Syllables

Syllables in Perflontus always contain exactly one vowel, which may be preceded
by at most one consonant, and followed by at most one consonant. This means that
an English speaker must take care to pronounce vowel and consonant clusters as
though they contain a syllable break, even if the cluster would represent a
valid English diphthong. For example ~wfro~ should be pronounced as ~OOF-roh~ and
not ~OO-froh~; and ~riqwe~ as ~REE-choo-ay~ and not ~REACH-way~ or ~REE-chway~. When in
doubt a consonant belongs to the same syllable as the vowel following it, e.g.
~i-qa~ not ~iq-a~.

Stress occurs on the syllable preceding a word's final consonant, not counting
any particles. Thus for verbs the stress will fall on the final syllable; for
nouns, usually on the penultimate or antepenultimate.

#+BEGIN_EXAMPLE
A- la- nu   Puf- lan- tu   ca-  tub.
ah-LAH-nuh  puff-LAHN-tuh  zhah-TUB.

Bu- nu   pa- i   to- re- lw- a   im   w- la- toc.
BUH-nuh  PAH-ee  toh-RAY-loo-ah  EEM  oo-lah-TOZH.
#+END_EXAMPLE
